import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { Download, Plus, RefreshCw, RotateCcw, Trash2, Upload } from 'lucide-react'
import { useEffect, useState, type FormEvent } from 'react'
import { useTranslation } from 'react-i18next'
import { toast } from 'sonner'
import { api, type Document, type Paged } from '../api'
import { CapabilityTags, EnabledPill, Field, Modal, SelectField, SkeletonRows } from '../components'
import { useProject } from '../project'
import { PageHeader, QueryError, ResourcePage, displayValue, formatDate } from './shared'

export default function ModelsPage() {
  const { t } = useTranslation()
  const [tab,setTab] = useState('models')
  return <div><div className="section-tabs" role="tablist" aria-label={t('models')}>{['models','routing','prices','catalog','subscriptions'].map((value)=><button key={value} role="tab" aria-selected={tab===value} onClick={()=>setTab(value)}>{t(value)}</button>)}</div>
    {tab==='models' && <ModelsPanel/>}
    {tab==='routing' && <><RoutingEditor/><RoutingPreview/></>}
    {tab==='prices' && <PricesPanel/>}
    {tab==='catalog' && <><CatalogMaintenance/><CatalogOverrideEditor/><ResourcePage resource="catalog-models" endpoint="/api/admin/v1/catalog/models" title={t('catalog')} description={t('catalogDescription')} empty={t('catalogEmpty')} immutable columns={[{key:'id',label:t('modelId'),mono:true},{key:'name',label:t('name'),mono:true},{key:'type',label:t('type')},{key:'capabilities',label:t('capabilities'),render:(value)=><CapabilityTags value={value}/>},{key:'provider_id',label:t('provider')}]} /></>}
    {tab==='subscriptions' && <CatalogSubscriptions/>}
  </div>
}

function useModelRelations(){const{project}=useProject();const channels=useQuery({queryKey:['channel-options',project.id],queryFn:()=>api<Paged<Document>>(`/api/admin/v1/projects/${project.id}/operations/channels?limit=500`)});const models=useQuery({queryKey:['model-options',project.id],queryFn:()=>api<Paged<Document>>(`/api/admin/v1/projects/${project.id}/operations/models?limit=500`)});return{channels:(channels.data?.data||[]).map(row=>({value:String(row.id),label:String(row.name)})),models:(models.data?.data||[]).map(row=>({value:String(row.id),label:String(row.public_name)}))}}
function ModelsPanel(){const{t}=useTranslation();const{channels}=useModelRelations();return <ResourcePage resource="models" title={t('models')} description={t('modelsDescription')} empty={t('modelEmpty')} createLabel={t('addModel')} columns={[{key:'public_name',label:t('publicModel'),mono:true},{key:'provider_name',label:t('channel')},{key:'upstream_name',label:t('upstreamModel'),mono:true},{key:'capabilities',label:t('capabilities'),render:(value)=><CapabilityTags value={value}/>},{key:'enabled',label:t('status'),render:(value)=><EnabledPill enabled={value}/>}]} fields={[{key:'provider_id',label:t('channel'),kind:'select',required:true,options:channels},{key:'public_name',label:t('publicModel'),required:true},{key:'upstream_name',label:t('upstreamModel'),required:true},{key:'capabilities',label:t('capabilities'),kind:'json',defaultValue:['chat','responses']},{key:'input_price_micros',label:t('inputPrice'),kind:'number',defaultValue:0},{key:'output_price_micros',label:t('outputPrice'),kind:'number',defaultValue:0},{key:'priority',label:t('priority'),kind:'number',defaultValue:100},{key:'enabled',label:t('status'),kind:'checkbox'}]}/>}
function RoutingEditor(){const{t}=useTranslation();const{channels,models}=useModelRelations();const any={value:'__any__',label:t('unrestricted')};return <ResourcePage resource="associations" title={t('routing')} description={t('routingDescription')} empty={t('routingEmpty')} createLabel={t('addRoute')} columns={[{key:'pattern',label:t('pattern'),mono:true},{key:'match_type',label:t('matchType')},{key:'model_name',label:t('model'),render:(value)=>value?String(value):t('unrestricted')},{key:'provider_name',label:t('channel'),render:(value)=>value?String(value):t('unrestricted')},{key:'priority',label:t('priority')},{key:'enabled',label:t('status'),render:(value)=><EnabledPill enabled={value}/>}]} fields={[{key:'model_id',label:t('model'),kind:'select',defaultValue:'__any__',options:[any,...models]},{key:'provider_id',label:t('channel'),kind:'select',defaultValue:'__any__',options:[any,...channels]},{key:'match_type',label:t('matchType'),kind:'select',options:['exact','regex','tag'].map(value=>({value,label:value}))},{key:'pattern',label:t('pattern'),required:true},{key:'conditions',label:t('conditions'),kind:'json',defaultValue:{version:1}},{key:'priority',label:t('priority'),kind:'number',defaultValue:100},{key:'weight',label:t('weight'),kind:'number',defaultValue:1},{key:'enabled',label:t('status'),kind:'checkbox'}]} normalize={(values,editing)=>({...values,...(editing?{id:editing.id}:{}),model_id:values.model_id==='__any__'?null:values.model_id,provider_id:values.provider_id==='__any__'?null:values.provider_id})}/>}
function PricesPanel(){const{t}=useTranslation();const{models}=useModelRelations();return <ResourcePage resource="prices" title={t('prices')} description={t('pricesDescription')} empty={t('priceEmpty')} createLabel={t('addPrice')} appendOnly columns={[{key:'model_name',label:t('model')},{key:'version',label:t('version')},{key:'valid_from',label:t('validFrom'),render:formatDate},{key:'valid_until',label:t('validUntil'),render:formatDate},{key:'schedule',label:t('schedule')}]} fields={[{key:'model_id',label:t('model'),kind:'select',required:true,options:models},{key:'components',label:t('priceComponents'),kind:'json',required:true,defaultValue:[{kind:'input',unit_size:1000000,unit_price_micros:0}]},{key:'schedule',label:t('schedule'),kind:'json',defaultValue:{version:1,rules:[]}}]}/>}

type Preview = { candidates: Document[]; decisions: Array<{stage:string;candidate:string|null;reason:string}>; estimated_tokens:number }
const humanRoutingStage=(value:string,t:(key:string)=>string)=>t(({access:'routingStageAccess',mapping:'routingStageMapping',association:'routingStageAssociation',eligibility:'routingStageEligibility',health:'routingStageHealth',endpoint:'routingStageEndpoint',strategy:'routingStageStrategy',protection:'routingStageProtection'} as Record<string,string>)[value]||'routingStageOther')
const humanRoutingReason=(value:string,t:(key:string)=>string)=>{const key=({project_and_model_allowed:'decisionAllowed',profile_mapping_applied:'decisionMapped',matched:'decisionMatched',ordered_candidate:'decisionOrdered',circuit_open:'decisionCircuitOpen',disabled:'decisionDisabled',tag_policy:'decisionTagPolicy',health_backoff:'decisionHealthBackoff',quota_exhausted:'decisionQuotaExhausted',unsupported_endpoint:'decisionUnsupported'} as Record<string,string>)[value];return key?t(key):value.replaceAll('_',' ')}
function RoutingPreview() {
  const { t } = useTranslation()
  const { project } = useProject()
  const [result,setResult] = useState<Preview|null>(null)
  const [keyId,setKeyId] = useState('')
  const [endpoint,setEndpoint] = useState('/v1/chat/completions')
  const keys = useQuery({ queryKey:['keys',project.id], queryFn:()=>api<Array<{id:string;name:string;enabled:boolean}>>(`/api/admin/v1/projects/${project.id}/api-keys`) })
  const preview = useMutation({ mutationFn:(body:unknown)=>api<Preview>(`/api/admin/v1/projects/${project.id}/routing-preview`,{method:'POST',body:JSON.stringify(body)}),onSuccess:setResult,onError:(error:Error)=>toast.error(error.message) })
  const submit=(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();const data=new FormData(event.currentTarget);preview.mutate({api_key_id:keyId,model:data.get('model'),endpoint,body:{}})}
  const keyOptions=(keys.data||[]).filter(key=>key.enabled).map(key=>({value:key.id,label:key.name}))
  useEffect(()=>{if(!keyOptions.some(option=>option.value===keyId))setKeyId(keyOptions[0]?.value||'')},[keyId,keyOptions.map(option=>option.value).join(',')])
  return <section className="routing-preview"><div><h2>{t('routingPreview')}</h2><p>{t('routingPreviewHint')}</p></div>{keys.isError?<QueryError retry={()=>void keys.refetch()}/>:keys.isLoading?<SkeletonRows count={2}/>:keyOptions.length===0?<p>{t('routingPreviewNeedsKey')}</p>:<form className="form-row" onSubmit={submit}><SelectField name="api_key_id" label={t('apiKey')} value={keyId} onValueChange={setKeyId} options={keyOptions}/><Field label={t('requestedModel')}><input name="model" required/></Field><SelectField name="endpoint" label={t('endpoint')} value={endpoint} onValueChange={setEndpoint} options={[{value:'/v1/chat/completions',label:'OpenAI chat'},{value:'/v1/responses',label:'OpenAI responses'},{value:'/v1/messages',label:'Anthropic messages'}]}/><button className="button button-primary" disabled={preview.isPending}>{t('preview')}</button></form>}{result&&<div className="route-explanation" aria-live="polite"><h3>{t('orderedCandidates')}</h3>{result.candidates.length?<ol>{result.candidates.map(row=><li key={String(row.id)}><strong>{displayValue(row.provider)}</strong><span>{displayValue(row.upstream_model)} · {displayValue(row.endpoint)} · {t('weight')} {displayValue(row.weight)}</span></li>)}</ol>:<p>{t('noRouteMatch')}</p>}<h3>{t('decisionLog')}</h3><ol>{result.decisions.map((decision,index)=><li key={`${decision.stage}-${index}`}><strong>{humanRoutingStage(decision.stage,t)}</strong><span>{humanRoutingReason(decision.reason,t)}{decision.candidate?` · ${decision.candidate}`:''}</span></li>)}</ol></div>}</section>
}

function CatalogMaintenance(){const{t}=useTranslation();const client=useQueryClient();const importCatalog=useMutation({mutationFn:(document:unknown)=>api('/api/admin/v1/catalog/import',{method:'POST',body:JSON.stringify(document)}),onSuccess:()=>{toast.success(t('saved'));void client.invalidateQueries({queryKey:['resource']})},onError:(error:Error)=>toast.error(error.message)});const submit=(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();const raw=String(new FormData(event.currentTarget).get('catalog')||'');try{importCatalog.mutate(JSON.parse(raw))}catch{toast.error(t('invalidJson'))}};return <section className="catalog-actions"><div><h2>{t('catalogTransfer')}</h2><p>{t('catalogTransferHint')}</p></div><a className="button" href="/api/admin/v1/catalog/export" download><Download size={17}/>{t('export')}</a><details><summary className="button"><Upload size={17}/>{t('import')}</summary><form onSubmit={submit}><Field label={t('catalogJson')}><textarea name="catalog" rows={8} required/></Field><button className="button button-primary">{t('validateAndImport')}</button></form></details></section>}

function CatalogOverrideEditor(){const{t}=useTranslation();const[kind,setKind]=useState('model');const mutate=useMutation({mutationFn:({id,document,remove}:{id:string;document?:unknown;remove?:boolean})=>api(`/api/admin/v1/catalog/overrides/${kind}/${encodeURIComponent(id)}`,{method:remove?'DELETE':'PUT',body:remove?undefined:JSON.stringify(document)}),onSuccess:()=>toast.success(t('saved')),onError:(error:Error)=>toast.error(error.message)});const submit=(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();const data=new FormData(event.currentTarget);try{const id=String(data.get('id'));const document=JSON.parse(String(data.get('document')));mutate.mutate({id,document:{...document,id}})}catch{toast.error(t('invalidJson'))}};return <details className="inline-tool"><summary>{t('localOverrides')}</summary><form className="form-stack" onSubmit={submit}><SelectField name="kind" label={t('type')} value={kind} onValueChange={setKind} options={[{value:'provider',label:t('provider')},{value:'model',label:t('model')}]}/><Field label="ID"><input name="id" required/></Field><Field label={t('overrideJson')}><textarea name="document" rows={8} required/></Field><div className="form-actions"><button type="button" className="button danger" onClick={(event)=>{const form=event.currentTarget.form;if(form){const id=String(new FormData(form).get('id'));if(id&&confirm(t('deleteConfirm')))mutate.mutate({id,remove:true})}}}>{t('delete')}</button><button className="button button-primary">{t('save')}</button></div></form></details>}

type CatalogSource = { id:string;name:string;url:string;priority:number;refresh_interval_secs:number;enabled:boolean;signature_policy:string;public_key:string|null;revision:number;last_success_at:number|null;last_error:string|null }
function CatalogSubscriptions() {
  const { t }=useTranslation(); const client=useQueryClient(); const [editing,setEditing]=useState<CatalogSource|null>(null); const [open,setOpen]=useState(false); const [snapshots,setSnapshots]=useState<{source:CatalogSource;data:Document[]}|null>(null)
  const query=useQuery({queryKey:['catalog-sources'],queryFn:()=>api<CatalogSource[]>('/api/admin/v1/catalog/sources')})
  const invalidate=()=>void client.invalidateQueries({queryKey:['catalog-sources']})
  const save=useMutation({mutationFn:({source,current}:{source:Omit<CatalogSource,'id'|'revision'|'last_success_at'|'last_error'>;current:CatalogSource|null})=>api(current?`/api/admin/v1/catalog/sources/${current.id}`:'/api/admin/v1/catalog/sources',{method:current?'PUT':'POST',body:JSON.stringify(current?{revision:current.revision,source}:source)}),onSuccess:()=>{invalidate();setOpen(false)},onError:(error:Error)=>toast.error(error.message)})
  const refresh=useMutation({mutationFn:(id:string)=>api(`/api/admin/v1/catalog/sources/${id}/refresh`,{method:'POST',body:'{}'}),onSuccess:invalidate,onError:(error:Error)=>toast.error(error.message)})
  const remove=useMutation({mutationFn:(id:string)=>api(`/api/admin/v1/catalog/sources/${id}`,{method:'DELETE'}),onSuccess:invalidate,onError:(error:Error)=>toast.error(error.message)})
  const loadSnapshots=async(source:CatalogSource)=>setSnapshots({source,data:await api<Document[]>(`/api/admin/v1/catalog/sources/${source.id}/snapshots`)})
  const rollback=useMutation({mutationFn:({source,snapshot}:{source:CatalogSource;snapshot:string})=>api(`/api/admin/v1/catalog/sources/${source.id}/rollback`,{method:'POST',body:JSON.stringify({revision:source.revision,snapshot_id:snapshot})}),onSuccess:()=>{invalidate();setSnapshots(null)},onError:(error:Error)=>toast.error(error.message)})
  const submit=(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();const data=new FormData(event.currentTarget);save.mutate({current:editing,source:{name:String(data.get('name')),url:String(data.get('url')),priority:Number(data.get('priority')),refresh_interval_secs:Number(data.get('refresh_interval_secs')),enabled:data.get('enabled')==='on',signature_policy:String(data.get('signature_policy')),public_key:String(data.get('public_key')||'')||null}})}
  return <><PageHeader title={t('subscriptions')} description={t('subscriptionsDescription')} action={<button className="button button-primary" onClick={()=>{setEditing(null);setOpen(true)}}><Plus size={17}/>{t('addSubscription')}</button>}/>{query.isError?<QueryError retry={()=>void query.refetch()}/>:query.isLoading?<SkeletonRows/>:query.data?.length?<div className="table-wrap"><table><thead><tr><th>{t('name')}</th><th>URL</th><th>{t('priority')}</th><th>{t('status')}</th><th>{t('lastError')}</th><th><span className="sr-only">{t('actions')}</span></th></tr></thead><tbody>{query.data.map(source=><tr key={source.id}><td><strong>{source.name}</strong></td><td><code>{source.url}</code></td><td>{source.priority}</td><td>{source.enabled?t('enabled'):t('disabled')}</td><td>{source.last_error||'—'}</td><td><div className="row-actions"><button className="icon-button" aria-label={`${t('refresh')} ${source.name}`} onClick={()=>refresh.mutate(source.id)}><RefreshCw size={16}/></button><button className="button button-quiet" onClick={()=>{setEditing(source);setOpen(true)}}>{t('edit')}</button><button className="icon-button" aria-label={`${t('rollback')} ${source.name}`} onClick={()=>void loadSnapshots(source)}><RotateCcw size={16}/></button><button className="icon-button danger" aria-label={`${t('delete')} ${source.name}`} onClick={()=>confirm(t('deleteConfirm'))&&remove.mutate(source.id)}><Trash2 size={16}/></button></div></td></tr>)}</tbody></table></div>:<p>{t('subscriptionEmpty')}</p>}
  <Modal open={open} onOpenChange={setOpen} title={editing?t('editSubscription'):t('addSubscription')}><form className="form-stack" onSubmit={submit}><Field label={t('name')}><input name="name" required defaultValue={editing?.name}/></Field><Field label="HTTPS URL"><input name="url" type="url" required defaultValue={editing?.url}/></Field><div className="form-row"><Field label={t('priority')}><input name="priority" type="number" required defaultValue={editing?.priority??100}/></Field><Field label={t('intervalSeconds')}><input name="refresh_interval_secs" type="number" min="60" max="2592000" required defaultValue={editing?.refresh_interval_secs??3600}/></Field></div><SelectField name="signature_policy" label={t('signaturePolicy')} value={editing?.signature_policy||'none'} onValueChange={()=>{}} options={['none','optional','required'].map(value=>({value,label:t(value)}))}/><Field label={t('publicKey')}><input name="public_key" defaultValue={editing?.public_key||''}/></Field><label className="check-field"><input name="enabled" type="checkbox" defaultChecked={editing?.enabled??true}/><span>{t('enabled')}</span></label><button className="button button-primary">{t('save')}</button></form></Modal>
  <Modal open={Boolean(snapshots)} onOpenChange={(value)=>!value&&setSnapshots(null)} title={t('rollback')} description={t('rollbackHint')}><div className="snapshot-list">{snapshots?.data.length?snapshots.data.map(snapshot=><button className="button" key={snapshot.id} onClick={()=>rollback.mutate({source:snapshots.source,snapshot:String(snapshot.id)})}>{displayValue(snapshot.version)} · {String(snapshot.digest).slice(0,12)}</button>):<p>{t('noSnapshots')}</p>}</div></Modal></>
}
