import {QueryClient,QueryClientProvider} from '@tanstack/react-query'
import {render,screen} from '@testing-library/react'
import userEvent from '@testing-library/user-event'
import {MemoryRouter} from 'react-router'
import {describe,expect,it,vi} from 'vitest'
import {ProjectProvider} from '../project'
import '../i18n'
import ModelsPage from './ModelsPage'
const reply=(value:unknown)=>Promise.resolve(new Response(JSON.stringify(value),{status:200,headers:{'Content-Type':'application/json'}}))
describe('routing association selectors',()=>{it('round-trips unrestricted model and channel as null',async()=>{const fetchMock=vi.fn((input:RequestInfo|URL,init?:RequestInit)=>{const path=String(input);if(path.endsWith('/projects'))return reply([{id:'p1',name:'P',slug:'p',owner_user_id:'u',is_default:true,enabled:true}]);if(path.includes('/permissions'))return reply(['*']);if(path.includes('/api-keys'))return reply([]);if(init?.method==='POST')return reply({id:'a1'});if(path.includes('/associations'))return reply({data:[{id:'a1',model_id:null,model_name:null,provider_id:null,provider_name:null,match_type:'exact',pattern:'global',conditions:{version:1},priority:1,weight:1,enabled:1}],total:1});return reply({data:[],total:0})});vi.stubGlobal('fetch',fetchMock);const client=new QueryClient({defaultOptions:{queries:{retry:false}}});render(<QueryClientProvider client={client}><MemoryRouter><ProjectProvider><ModelsPage/></ProjectProvider></MemoryRouter></QueryClientProvider>);await userEvent.click(await screen.findByRole('tab',{name:'Model routing'}));await userEvent.click((await screen.findAllByRole('button',{name:'Edit'}))[0]);expect(screen.getAllByRole('combobox').filter(item=>item.textContent?.includes('Unrestricted')).length).toBeGreaterThanOrEqual(2);await userEvent.click(screen.getByRole('button',{name:'Save'}));await vi.waitFor(()=>{const call=fetchMock.mock.calls.find(([,init])=>init?.method==='POST');const body=JSON.parse(String(call?.[1]?.body));expect(body.model_id).toBeNull();expect(body.provider_id).toBeNull()})})})
