import { useQuery } from '@tanstack/react-query'
import { Activity, Pause, Play } from 'lucide-react'
import { useState } from 'react'
import { useTranslation } from 'react-i18next'
import { Link, useParams } from 'react-router'
import { api, type RequestDetail, type RequestItem } from '../api'
import { EmptyState, Field, SkeletonRows, Status } from '../components'
import { projectOperationPath, useProject } from '../project'
import { PageHeader, QueryError, ResourcePage, displayValue, formatDate } from './shared'

export default function OperationsPage(){const{t}=useTranslation();const[tab,setTab]=useState('requests');return <div><div className="section-tabs" role="tablist" aria-label={t('operations')}>{['requests','executions','threads','traces','usage','costItems','audit'].map(value=><button key={value} role="tab" aria-selected={tab===value} onClick={()=>setTab(value)}>{t(value)}</button>)}</div>{tab==='requests'&&<RequestList/>}{tab==='executions'&&<ResourcePage resource="executions" title={t('executions')} description={t('executionsDescription')} empty={t('executionEmpty')} immutable columns={[{key:'status',label:t('status')},{key:'request_id',label:t('requestId'),mono:true},{key:'provider_id',label:t('provider'),mono:true},{key:'attempt',label:t('attempt')},{key:'latency_ms',label:t('latency')},{key:'retry_reason',label:t('retryReason')}]} />}{tab==='threads'&&<ResourcePage resource="threads" title={t('threads')} description={t('threadsDescription')} empty={t('threadEmpty')} immutable columns={[{key:'id',label:t('threadId'),mono:true},{key:'external_id',label:t('externalId'),mono:true},{key:'api_key_id',label:t('key'),mono:true},{key:'created_at',label:t('time'),render:formatDate}]} />}{tab==='traces'&&<ResourcePage resource="traces" title={t('traces')} description={t('tracesDescription')} empty={t('traceEmpty')} immutable columns={[{key:'status',label:t('status')},{key:'id',label:t('trace'),mono:true,render:(value)=><Link to={`/operations/traces/${value}`}>{String(value)}</Link>},{key:'thread_id',label:t('threadId'),mono:true},{key:'started_at',label:t('startedAt'),render:formatDate},{key:'finished_at',label:t('finishedAt'),render:formatDate}]} />}{tab==='usage'&&<ResourcePage resource="usage" title={t('usage')} description={t('usageDescription')} empty={t('usageEmpty')} immutable columns={[{key:'execution_id',label:t('executionId'),mono:true},{key:'input_tokens',label:t('inputTokens')},{key:'output_tokens',label:t('outputTokens')},{key:'cache_read_tokens',label:t('cacheTokens')},{key:'cost_micros',label:t('cost')},{key:'settlement_kind',label:t('settlement')}]} />}{tab==='costItems'&&<ResourcePage resource="cost-items" title={t('costItems')} description={t('costDescription')} empty={t('costEmpty')} immutable columns={[{key:'usage_id',label:t('usageId'),mono:true},{key:'component_id',label:t('component'),mono:true},{key:'quantity',label:t('quantity')},{key:'subtotal_micros',label:t('cost')}]} />}{tab==='audit'&&<ResourcePage resource="audit" title={t('audit')} description={t('auditDescription')} empty={t('auditEmpty')} immutable columns={[{key:'action',label:t('action')},{key:'resource_type',label:t('type')},{key:'resource_id',label:t('resourceId'),mono:true},{key:'actor_user_id',label:t('actor'),mono:true},{key:'created_at',label:t('time'),render:formatDate}]} />}</div>}

function RequestList(){const{t}=useTranslation();const{project}=useProject();const[paused,setPaused]=useState(false);const[filters,setFilters]=useState({status:'',provider:'',model:''});const params=new URLSearchParams({limit:'200'});if(filters.status)params.set('status_code',filters.status);if(filters.provider)params.set('provider',filters.provider);if(filters.model)params.set('model',filters.model);const query=useQuery({queryKey:['requests',project.id,filters],queryFn:()=>api<RequestItem[]>(`/api/admin/v1/projects/${encodeURIComponent(project.id)}/observability/requests?${params}`),refetchInterval:paused?false:15000});return <><PageHeader title={t('requests')} description={`${t('requestsDescription')} · ${query.dataUpdatedAt?new Date(query.dataUpdatedAt).toLocaleTimeString():'—'}`} action={<button className="button" onClick={()=>setPaused(value=>!value)}>{paused?<Play size={16}/>:<Pause size={16}/>} {paused?t('resume'):t('pause')}</button>}/><div className="filter-bar"><Field label={t('statusCode')}><input value={filters.status} onChange={e=>setFilters({...filters,status:e.target.value})} inputMode="numeric"/></Field><Field label={t('provider')}><input value={filters.provider} onChange={e=>setFilters({...filters,provider:e.target.value})}/></Field><Field label={t('model')}><input value={filters.model} onChange={e=>setFilters({...filters,model:e.target.value})}/></Field></div>{query.isError?<QueryError retry={()=>void query.refetch()}/>:query.isLoading?<SkeletonRows/>:!query.data?.length?<EmptyState icon={<Activity/>} title={t('requests')} copy={t('noRequests24h')}/>:<div className="table-wrap" role="region" aria-label={t('requests')} tabIndex={0}><table><thead><tr><th>{t('status')}</th><th>{t('model')}</th><th>{t('provider')}</th><th>{t('endpoint')}</th><th>{t('latency')}</th><th>{t('cost')}</th><th>{t('startedAt')}</th></tr></thead><tbody>{query.data.map(row=><tr key={row.request_id}><td><Link to={`/operations/requests/${row.request_id}`}><Status code={row.status_code}/></Link></td><td><strong>{displayValue(row.requested_model)}</strong></td><td>{displayValue(row.provider)}</td><td><code>{row.endpoint}</code></td><td>{row.latency_ms>=0?`${row.latency_ms} ms`:'—'}</td><td>${(row.cost_micros/1_000_000).toFixed(6)}</td><td>{formatDate(row.started_at)}</td></tr>)}</tbody></table></div>}</>}

export function RequestDetailPage(){const{id}=useParams();const{t}=useTranslation();const{project}=useProject();const query=useQuery({queryKey:['request',project.id,id],queryFn:()=>api<RequestDetail>(`/api/admin/v1/projects/${encodeURIComponent(project.id)}/observability/requests/${id}`),enabled:Boolean(id)});return <><PageHeader title={t('requestDetail')} description={id}/><Link className="back-link" to="/operations">← {t('backToRequests')}</Link>{query.isError?<QueryError retry={()=>void query.refetch()}/>:query.isLoading?<SkeletonRows/>:query.data&&<TraceFacts data={query.data}/>}</>}
export function TraceDetailPage(){const{id}=useParams();const{t}=useTranslation();const{project}=useProject();const query=useQuery({queryKey:['trace',project.id,id],queryFn:()=>api<Record<string,unknown>>(projectOperationPath(project.id,'traces',id)),enabled:Boolean(id)});return <><PageHeader title={t('traceDetail')} description={id}/><Link className="back-link" to="/operations">← {t('backToTraces')}</Link>{query.isError?<QueryError retry={()=>void query.refetch()}/>:query.isLoading?<SkeletonRows/>:query.data&&<section className="trace-sheet"><dl>{Object.entries(query.data).map(([key,value])=><div key={key}><dt>{key.replaceAll('_',' ')}</dt><dd>{displayValue(value)}</dd></div>)}</dl></section>}</>}
function TraceFacts({data}:{data:RequestDetail}){const{t}=useTranslation();return <div className="detail-stack"><section className="trace-sheet"><dl><div><dt>{t('status')}</dt><dd><Status code={data.status_code}/></dd></div><div><dt>{t('trace')}</dt><dd><code>{data.trace_id}</code></dd></div><div><dt>{t('model')}</dt><dd>{displayValue(data.requested_model)} → {displayValue(data.resolved_model)}</dd></div><div><dt>{t('provider')}</dt><dd>{displayValue(data.provider)}</dd></div><div><dt>{t('latency')}</dt><dd>{data.latency_ms>=0?`${data.latency_ms} ms`:'—'}</dd></div><div><dt>TTFT</dt><dd>{data.ttft_ms==null?'—':`${data.ttft_ms} ms`}</dd></div><div><dt>{t('tokens')}</dt><dd>{data.input_tokens} / {data.output_tokens}</dd></div><div><dt>{t('cost')}</dt><dd>${(data.cost_micros/1_000_000).toFixed(6)}</dd></div></dl></section>{data.payload_captured?<><Json title={t('requestPayload')} value={data.request_json}/><Json title={t('responsePayload')} value={data.response_json}/></>:<p className="notice">{t('payloadDisabledHint')}</p>}</div>}
function Json({title,value}:{title:string;value:string|null}){const{t}=useTranslation();const download=()=>{if(!value)return;const url=URL.createObjectURL(new Blob([value],{type:'application/json'}));const anchor=document.createElement('a');anchor.href=url;anchor.download=`${title.toLowerCase().replaceAll(' ','-')}.json`;anchor.click();URL.revokeObjectURL(url)};return <section className="json-block"><div className="panel-heading"><h2>{title}</h2>{value&&<button className="button button-quiet" onClick={download}>{t('download')}</button>}</div><pre>{value?JSON.stringify(JSON.parse(value),null,2):'—'}</pre></section>}
