import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { useState, type FormEvent } from 'react'
import { useTranslation } from 'react-i18next'
import { toast } from 'sonner'
import { api } from '../api'
import { Field, EnabledPill, SelectField, SkeletonRows } from '../components'
import { useProject } from '../project'
import { useTheme, type Accent, type ColorMode } from '../theme'
import { PageHeader, QueryError, ResourcePage } from './shared'

export default function SystemPage() {
  const {t}=useTranslation(); const[tab,setTab]=useState('appearance')
  return <div><div className="section-tabs" role="tablist" aria-label={t('systemSettings')}>{['appearance','orchestrationSettings','requestLogging','storage','backups','webhooks','jobs','retention'].map(value=><button key={value} role="tab" aria-selected={tab===value} onClick={()=>setTab(value)}>{t(value)}</button>)}</div>
    {tab==='appearance'&&<><Appearance/><BrandingSettings/></>}
    {tab==='orchestrationSettings'&&<OrchestrationSettings/>}
    {tab==='requestLogging'&&<LoggingPolicy/>}
    {tab==='storage'&&<ResourcePage resource="storage" title={t('storage')} description={t('storageDescription')} empty={t('storageEmpty')} createLabel={t('addStorage')} columns={[{key:'name',label:t('name')},{key:'kind',label:t('type')},{key:'config',label:t('configuration')},{key:'revision',label:t('revision')},{key:'enabled',label:t('status'),render:(value)=><EnabledPill enabled={value}/>}]} fields={[{key:'name',label:t('name'),required:true},{key:'config',label:t('configuration'),kind:'json',defaultValue:{kind:'local',directory:'backups'}},{key:'secret',label:t('storageSecret'),kind:'json',omitWhenBlank:true},{key:'enabled',label:t('enabled'),kind:'checkbox'},{key:'revision',label:t('revision'),kind:'number',defaultValue:0}]}/>}
    {tab==='backups'&&<BackupPanel/>}
    {tab==='webhooks'&&<ResourcePage resource="webhooks" title={t('webhooks')} description={t('webhooksDescription')} empty={t('webhookEmpty')} createLabel={t('addWebhook')} columns={[{key:'name',label:t('name')},{key:'url',label:'URL',mono:true},{key:'subscriptions',label:t('events')},{key:'enabled',label:t('status'),render:(value)=><EnabledPill enabled={value}/>}]} fields={[{key:'name',label:t('name'),required:true},{key:'url',label:'URL',required:true},{key:'events',label:t('events'),kind:'json',defaultValue:['channel.disabled','quota.exhausted','request.failed']},{key:'headers',label:t('publicHeaders'),kind:'json',defaultValue:{}},{key:'secret_headers',label:t('secretHeaders'),kind:'json',omitWhenBlank:true},{key:'body',label:t('bodyTemplate'),kind:'json',defaultValue:'$event'},{key:'enabled',label:t('enabled'),kind:'checkbox'}]}/>}
    {tab==='jobs'&&<ResourcePage resource="jobs" title={t('jobs')} description={t('jobsDescription')} empty={t('jobEmpty')} immutable columns={[{key:'kind',label:t('type')},{key:'status',label:t('status')},{key:'attempts',label:t('attempts')},{key:'due_at',label:t('dueAt')},{key:'error_code',label:t('lastError')}]} />}
    {tab==='retention'&&<ResourcePage resource="retention" title={t('retention')} description={t('retentionDescription')} empty={t('retentionEmpty')} createLabel={t('addPolicy')} columns={[{key:'resource_type',label:t('type')},{key:'retention_days',label:t('retentionDays')},{key:'retain_payloads',label:t('retainPayloads')}]} fields={[{key:'resource_type',label:t('type'),kind:'select',options:['requests','payloads','probes','quota'].map(value=>({value,label:t(value)}))},{key:'retention_days',label:t('retentionDays'),kind:'number',defaultValue:30},{key:'retain_payloads',label:t('retainPayloads'),kind:'checkbox'}]}/>}
  </div>
}

function Appearance(){const{t,i18n}=useTranslation();const{mode,accent,setMode,setAccent}=useTheme();return <><PageHeader title={t('appearance')} description={t('appearanceDescription')}/><section className="settings-section"><div><h2>{t('interface')}</h2><p>{t('appearanceHint')}</p></div><div className="settings-controls"><SelectField label={t('colorMode')} value={mode} onValueChange={value=>setMode(value as ColorMode)} options={(['system','light','dark'] as const).map(value=>({value,label:t(value)}))}/><SelectField label={t('accentTheme')} value={accent} onValueChange={value=>setAccent(value as Accent)} options={(['bronze','slate','jade'] as const).map(value=>({value,label:t(value)}))}/><SelectField label={t('language')} value={i18n.language} onValueChange={value=>void i18n.changeLanguage(value)} options={[{value:'zh-CN',label:'简体中文'},{value:'en',label:'English'}]}/></div></section></>}

type Branding = {instance_name:string;branding_name:string;favicon_url:string;onboarding_complete:boolean}
function BrandingSettings(){const{t}=useTranslation();const client=useQueryClient();const query=useQuery({queryKey:['system-settings'],queryFn:()=>api<Branding>('/api/admin/v1/settings/system')});const save=useMutation({mutationFn:(body:Branding)=>api('/api/admin/v1/settings/system',{method:'PUT',body:JSON.stringify(body)}),onSuccess:()=>{toast.success(t('saved'));void client.invalidateQueries({queryKey:['system-settings']});void client.invalidateQueries({queryKey:['bootstrap']})},onError:(error:Error)=>toast.error(error.message)});if(query.isError)return <QueryError retry={()=>void query.refetch()}/>;if(query.isLoading||!query.data)return <SkeletonRows count={2}/>;const submit=(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();const data=new FormData(event.currentTarget);save.mutate({instance_name:String(data.get('instance_name')),branding_name:String(data.get('branding_name')),favicon_url:String(data.get('favicon_url')),onboarding_complete:data.get('onboarding_complete')==='on'})};return <section className="settings-section"><div><h2>{t('branding')}</h2><p>{t('brandingHint')}</p></div><form className="form-stack" onSubmit={submit}><Field label={t('instanceName')}><input name="instance_name" defaultValue={query.data.instance_name} required/></Field><Field label={t('brandingName')}><input name="branding_name" defaultValue={query.data.branding_name} required/></Field><Field label={t('faviconUrl')}><input name="favicon_url" defaultValue={query.data.favicon_url} required/></Field><label className="check-field"><input name="onboarding_complete" type="checkbox" defaultChecked={query.data.onboarding_complete}/><span>{t('onboardingComplete')}</span></label><button className="button button-primary">{t('save')}</button></form></section>}

type OrchestrationDocument={version:number;affinity_rules:unknown[];session_compaction:Record<string,unknown>}
function OrchestrationSettings(){const{t}=useTranslation();const{project}=useProject();const client=useQueryClient();const path=`/api/admin/v1/projects/${project.id}/settings/orchestration`;const query=useQuery({queryKey:['orchestration-settings',project.id],queryFn:()=>api<OrchestrationDocument>(path)});const save=useMutation({mutationFn:(body:OrchestrationDocument)=>api(path,{method:'PUT',body:JSON.stringify(body)}),onSuccess:()=>{toast.success(t('saved'));void client.invalidateQueries({queryKey:['orchestration-settings',project.id]})},onError:(error:Error)=>toast.error(error.message)});if(query.isLoading||!query.data)return <SkeletonRows/>;if(query.isError)return <QueryError retry={()=>void query.refetch()}/>;const submit=(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();const data=new FormData(event.currentTarget);try{save.mutate({version:1,affinity_rules:JSON.parse(String(data.get('affinity_rules'))),session_compaction:JSON.parse(String(data.get('session_compaction')))})}catch{toast.error(t('invalidJson'))}};return <><PageHeader title={t('orchestrationSettings')} description={t('orchestrationSettingsHint')}/><form className="panel form-stack" onSubmit={submit}><Field label={t('affinityRules')} hint={t('affinityRulesHint')}><textarea name="affinity_rules" rows={12} defaultValue={JSON.stringify(query.data.affinity_rules,null,2)} required/></Field><Field label={t('sessionCompaction')} hint={t('sessionCompactionHint')}><textarea name="session_compaction" rows={10} defaultValue={JSON.stringify(query.data.session_compaction,null,2)} required/></Field><button className="button button-primary">{t('save')}</button></form></>}

type Policy={enabled:boolean;default_level:string;key_override_enabled:boolean;key_disable_allowed:boolean}
function LoggingPolicy(){const{t}=useTranslation();const client=useQueryClient();const query=useQuery({queryKey:['logging-policy'],queryFn:()=>api<Policy>('/api/admin/v1/settings/request-logging')});const update=useMutation({mutationFn:(policy:Policy)=>api('/api/admin/v1/settings/request-logging',{method:'PUT',body:JSON.stringify(policy)}),onSuccess:()=>{toast.success(t('saved'));void client.invalidateQueries({queryKey:['logging-policy']})},onError:(error:Error)=>toast.error(error.message)});if(query.isError)return <QueryError retry={()=>void query.refetch()}/>;if(query.isLoading||!query.data)return <SkeletonRows/>;const policy=query.data;return <><PageHeader title={t('requestLogging')} description={t('requestLoggingDescription')}/><section className="policy-form"><label className="check-field"><input type="checkbox" checked={policy.enabled} onChange={event=>update.mutate({...policy,enabled:event.target.checked})}/><span><strong>{t('enableRequestLogging')}</strong><small>{t('enableRequestLoggingHint')}</small></span></label><SelectField label={t('defaultLevel')} value={policy.default_level} onValueChange={value=>update.mutate({...policy,default_level:value})} options={['off','metadata','redacted_body','full_body'].map(value=>({value,label:t(value)}))}/><label className="check-field"><input type="checkbox" checked={policy.key_override_enabled} onChange={event=>update.mutate({...policy,key_override_enabled:event.target.checked})}/><span>{t('allowKeyOverrides')}</span></label><label className="check-field"><input type="checkbox" checked={policy.key_disable_allowed} onChange={event=>update.mutate({...policy,key_disable_allowed:event.target.checked})}/><span>{t('allowKeyDisable')}</span></label></section></>}

function BackupPanel() {
  const {t}=useTranslation(); const {project}=useProject(); const [artifact,setArtifact]=useState(''); const base=`/api/admin/v1/projects/${project.id}/backup`
  const run=useMutation({mutationFn:({path,body}:{path:string;body:unknown})=>api<unknown>(`${base}/${path}`,{method:'POST',body:JSON.stringify(body)}),onSuccess:(value)=>{setArtifact(JSON.stringify(value,null,2));toast.success(t('saved'))},onError:(error:Error)=>toast.error(error.message)})
  const resources=(value:FormDataEntryValue|null)=>String(value||'').split(',').map(item=>item.trim()).filter(Boolean)
  const exportNow=(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();const data=new FormData(event.currentTarget);run.mutate({path:'export',body:{resources:resources(data.get('resources'))}})}
  const restore=(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();const data=new FormData(event.currentTarget);try{run.mutate({path:'restore',body:{artifact:JSON.parse(String(data.get('artifact'))),strategy:data.get('strategy')}})}catch{toast.error(t('invalidJson'))}}
  const deliver=(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();const data=new FormData(event.currentTarget);run.mutate({path:'run',body:{targets:resources(data.get('targets')),resources:resources(data.get('resources'))}})}
  return <><PageHeader title={t('backups')} description={t('backupsDescription')}/><div className="backup-grid"><form className="panel form-stack" onSubmit={exportNow}><h2>{t('exportBackup')}</h2><Field label={t('resources')} hint={t('resourcesHint')}><input name="resources" required/></Field><button className="button button-primary">{t('export')}</button></form><form className="panel form-stack" onSubmit={deliver}><h2>{t('deliverBackup')}</h2><Field label={t('targetIds')}><input name="targets" required/></Field><Field label={t('resources')}><input name="resources" required/></Field><button className="button button-primary">{t('runNow')}</button></form><form className="panel form-stack" onSubmit={restore}><h2>{t('restoreBackup')}</h2><Field label={t('artifactJson')}><textarea name="artifact" required defaultValue={artifact}/></Field><label className="field"><span className="field-label">{t('conflictStrategy')}</span><select name="strategy" defaultValue="fail"><option value="fail">fail</option><option value="skip">skip</option><option value="overwrite">overwrite</option></select></label><button className="button">{t('restore')}</button></form></div><ResourcePage resource="schedules" title={t('backupSchedules')} description={t('backupScheduleHint')} empty={t('backupEmpty')} createLabel={t('addSchedule')} columns={[{key:'kind',label:t('type')},{key:'interval_secs',label:t('interval')},{key:'next_run_at',label:t('nextRun')},{key:'enabled',label:t('status'),render:(value)=><EnabledPill enabled={value}/>},{key:'revision',label:t('revision')}]} fields={[{key:'kind',label:t('type'),kind:'select',options:[{value:'automatic_backup',label:t('automaticBackup')},{value:'backup_retention',label:t('backupRetention')},{value:'probe',label:t('probe')},{value:'quota',label:t('quota')}]},{key:'payload',label:t('configuration'),kind:'json',defaultValue:{targets:[],resources:[]}},{key:'interval_secs',label:t('intervalSeconds'),kind:'number',defaultValue:3600},{key:'enabled',label:t('enabled'),kind:'checkbox'},{key:'revision',label:t('revision'),kind:'number',defaultValue:0}]}/></>
}
