import i18n from 'i18next'
import { initReactI18next } from 'react-i18next'

const zh = {
  translation: {
    unrestricted:'不限制',viewTrace:'查看追踪',
    invitationInvalid:'邀请无效或已过期',backToLogin:'返回登录',acceptInvitation:'接受邀请',inspectInvitation:'检查邀请',invitedAs:'受邀邮箱：{{email}}',displayName:'显示名称',invitationCreated:'邀请已创建',invitationOneTime:'此链接只显示一次，请立即安全发送给受邀者。',accepted:'已接受',pending:'待处理',noSearchResults:'没有匹配结果',clearFilters:'清除筛选条件',pagination:'分页',previous:'上一页',next:'下一页',pageSize:'每页数量',copyId:'复制 ID',orchestrationSettings:'编排设置',orchestrationSettingsHint:'管理会话亲和与可选会话压缩。',affinityRules:'亲和规则 JSON',affinityRulesHint:'最多 64 条，TTL 为 1–86400 秒。',sessionCompaction:'会话压缩 JSON',sessionCompactionHint:'启用前配置阈值、保留条数和原生或摘要模型。',channelPolicies:'渠道策略',channelPoliciesHint:'管理端点映射、模型规则、参数覆盖、重试和自动停用。',channelPoliciesEmpty:'尚无渠道策略。',noProfile:'不使用配置档',outcome:'结果',duration:'耗时',viewDetails:'查看详情',unknownProvider:'未知供应商',noRetry:'未重试',rawIdentifiers:'原始标识',statusSucceeded:'成功',statusFinished:'已结束',statusFailed:'失败',statusRunning:'运行中',statusPending:'等待中',statusCancelled:'已取消',statusInterrupted:'已中断',statusUnknown:'未知',routingStageAccess:'访问检查',routingStageMapping:'模型映射',routingStageAssociation:'路由规则',routingStageEligibility:'可用性检查',routingStageHealth:'健康检查',routingStageEndpoint:'端点能力',routingStageStrategy:'排序策略',routingStageProtection:'提示词防护',routingStageOther:'其他决策',decisionAllowed:'项目与模型访问已允许',decisionMapped:'已应用配置档模型映射',decisionMatched:'规则已匹配',decisionOrdered:'候选已按策略排序',decisionCircuitOpen:'熔断器处于打开状态',decisionDisabled:'渠道或模型已停用',decisionTagPolicy:'标签策略不允许此候选',decisionHealthBackoff:'渠道处于健康退避期',decisionQuotaExhausted:'供应商配额已耗尽',decisionUnsupported:'端点或能力不受支持',decisionOther:'{{code}}',onboardingTitle:'完成首次配置',onboardingHint:'添加渠道、凭据和模型路由后即可开始发送请求。',
    localOverrides:'本地目录覆盖',overrideJson:'覆盖条目 JSON',
    expiresAtEpoch:'到期时间（Unix 秒）',
    download:'下载',
    identities:'OIDC 身份',identitiesDescription:'显式关联现有用户与已验证的供应商主体。',oidcProviderId:'OIDC 供应商 ID',subject:'主体标识',claims:'声明 JSON',linkIdentity:'关联身份',
    oidc:'OIDC',channel:'渠道',
    noAccessibleProject:'没有可访问的项目。',
    assignments:'成员与角色分配',projectMembership:'项目成员',roleBinding:'角色绑定',userId:'用户 ID',assign:'分配',
    project:'项目',enable:'启用',disable:'停用',apply:'应用',bulkActions:'批量启用或停用',resourceIds:'资源 ID（逗号分隔）',jobQueued:'任务已入队',collectQuota:'采集配额',runProbe:'运行探测',usePreset:'使用预设',preview:'预览',orderedCandidates:'候选顺序',decisionLog:'决策说明',routingPreviewNeedsKey:'请先为项目创建一把已启用的 API 密钥。',refresh:'刷新',rollback:'回滚',editSubscription:'编辑订阅',rollbackHint:'选择一个已验证快照作为活动目录。',noSnapshots:'没有可回滚的快照。',signaturePolicy:'签名策略',publicKey:'Ed25519 公钥',none:'无',optional:'可选',required:'必需',keyLoggingPolicy:'密钥请求日志策略',keyId:'密钥 ID',inherit:'继承站点策略',editKey:'编辑 API 密钥',modelMappings:'模型映射',allowedModels:'允许模型',branding:'品牌与引导',brandingHint:'配置实例名称、浏览器图标和首次引导状态。',brandingName:'品牌名称',faviconUrl:'浏览器图标 URL',onboardingComplete:'已完成首次引导',exportBackup:'导出备份',deliverBackup:'投递备份',restoreBackup:'恢复备份',resources:'资源',resourcesHint:'使用数据库资源名，以逗号分隔。',targetIds:'存储目标 ID',runNow:'立即运行',artifactJson:'备份产物 JSON',conflictStrategy:'冲突策略',restore:'恢复',backupSchedules:'自动计划',backupScheduleHint:'持久、带修订号的自动备份与保留计划。',
    product: '鲮鲤', productSubtitle: 'AI API 网关', overview: '概览', providers: '供应商', models: '模型与路由', apiKeys: 'API 密钥', requests: '请求记录', settings: '设置',
    signOut: '退出登录', menu: '菜单', close: '关闭', skipToContent: '跳到主要内容', dataTable: '数据表', prefix: '前缀', trace: '追踪 ID', requestPayload: '请求正文', responsePayload: '响应正文', add: '添加', cancel: '取消', save: '保存', delete: '删除', copy: '复制', copied: '已复制', loading: '加载中…', retry: '重试', noData: '暂无数据',
    setupTitle: '初始化鲮鲤', setupIntro: '创建首位管理员。完成后即可添加上游供应商并签发虚拟 API 密钥。', instanceName: '实例名称', email: '邮箱', password: '密码', passwordHint: '至少 12 个字符', createAdmin: '创建管理员',
    loginTitle: '登录鲮鲤', loginIntro: '进入你的 AI API 控制平面。', signIn: '登录',
    last24h: '过去 24 小时', totalRequests: '请求总量', errorRate: '错误率', p95Latency: 'P95 延迟', tokenUsage: 'Token 用量', cost: '成本', requestTrend: '请求趋势', recentRequests: '最近请求',
    failedRequests: '失败 {{count}} 次', perRequest: '每次请求', requestTrendHint: '按小时统计的请求量', chartTooltipHint: '将指针移到折线上查看具体小时。',
    providerName: '供应商名称', providerType: '类型', baseUrl: 'Base URL', upstreamApiKey: '上游 API Key', addProvider: '添加供应商', providerEmpty: '先添加一个上游供应商。密钥将加密保存在本机。',
    publicModel: '公开模型名', upstreamModel: '上游模型名', provider: '供应商', priority: '优先级', inputPrice: '输入价格', outputPrice: '输出价格', addModel: '添加模型', priceHint: '微美元 / 百万 Token', modelEmpty: '添加模型映射后，客户端即可使用统一模型名调用。',
    keyName: '密钥名称', budget: '预算', addKey: '创建 API 密钥', keyCreated: 'API 密钥已创建', keyCreatedHint: '它只显示一次，请立即复制并安全保存。', keyEmpty: '为客户端或团队创建一把虚拟密钥。', lastUsed: '最后使用', never: '从未',
    status: '状态', endpoint: '端点', startedAt: '开始时间', latency: '延迟', model: '模型', tokens: 'Token', requestDetail: '请求详情', payloadDisabled: '敏感负载采集已关闭', payloadDisabledHint: '这是默认的安全设置。可观测性仍会记录元数据、用量和延迟。',
    appearance: '外观', colorMode: '明暗模式', skin: '界面风格', palette: '配色', accentTheme: '强调色', language: '语言', system: '跟随系统', light: '浅色', dark: '深色', bronze: '铜棕', slate: '石板蓝', jade: '玉青', skinHint: '当前风格源自风格库的 {{basis}}（材质 {{material}}，推荐 {{mode}} 模式）；切换风格会同时套用它的推荐配色与模式。',
    workspace:'工作区',observe:'可观测性',administration:'管理',primaryNavigation:'主导航',channels:'渠道',operations:'运行记录',access:'访问控制',prompts:'提示词',playground:'调试台',systemSettings:'系统设置',
    actions:'操作',edit:'编辑',saved:'已保存',deleted:'已删除',search:'搜索',retryHint:'检查连接后重试。',invalidJson:'JSON 格式无效。',viewAll:'查看全部',name:'名称',enabled:'已启用',disabled:'已停用',type:'类型',version:'版本',statusCode:'状态码',time:'时间',ready:'就绪',catalogOnly:'仅目录信息',
    overviewEmptyTitle:'过去 24 小时没有请求',overviewEmptyCopy:'配置第一个渠道和模型路由，然后从客户端发送请求。',configureChannel:'配置渠道',noRequests24h:'过去 24 小时没有可显示的请求。',
    credentials:'凭据',probes:'探测',quotas:'配额',presets:'预设',channelsDescription:'管理上游渠道、状态和端点。',channelEmpty:'添加渠道后即可绑定多个加密凭据。',addChannel:'添加渠道',credentialsDescription:'同一渠道可按优先级使用多份加密凭据。',credentialEmpty:'为渠道添加第一份凭据。',addCredential:'添加凭据',credentialType:'凭据类型',channelId:'渠道 ID',suffix:'尾号',secret:'密钥',secretUpdateHint:'密钥仅在创建或轮换时提交，保存后无法取回。',advancedSettings:'高级设置',probesDescription:'查看渠道健康探测及延迟。',probeEmpty:'尚无探测结果。',quotasDescription:'查看供应商配额快照。',quotaEmpty:'尚无配额快照。',remaining:'剩余量',periodEnd:'周期结束',presetsDescription:'内置离线供应商目录，可用于配置渠道。',presetEmpty:'目录中没有匹配的供应商。',adapter:'适配器',
    routing:'模型路由',prices:'价格',catalog:'模型目录',subscriptions:'目录订阅',modelsDescription:'管理公开模型、能力和上游映射。',capabilities:'能力',routingDescription:'用精确、正则或标签规则编排候选渠道。',routingEmpty:'添加首条模型关联规则。',addRoute:'添加路由',matchType:'匹配类型',pattern:'模式',weight:'权重',modelId:'模型 ID',conditions:'条件',routingPreview:'路由预览与解释',routingPreviewHint:'输入请求模型和标签，按优先级预览匹配规则。',requestedModel:'请求模型',tags:'标签（逗号分隔）',noRouteMatch:'当前输入没有匹配的规则。',routeExplanation:'优先级 {{priority}}，权重 {{weight}}，渠道 {{channel}}',pricesDescription:'价格版本一经使用即保持不可变。',priceEmpty:'尚未创建价格版本。',addPrice:'添加价格版本',validFrom:'生效时间',validUntil:'失效时间',schedule:'价格计划',priceComponents:'计价组件',catalogDescription:'查看目录模型、能力和来源。',catalogEmpty:'目录中没有匹配的模型。',catalogResultCount:'共 {{count}} 个模型',moreCapabilities:'另有 {{count}} 项',catalogTransfer:'目录导入与导出',catalogTransferHint:'导入会先校验，再以原子方式激活。',export:'导出',import:'导入',catalogJson:'目录 JSON',validateAndImport:'校验并导入',subscriptionsDescription:'管理 HTTPS 目录订阅、签名和刷新顺序。',subscriptionEmpty:'尚未配置目录订阅。',addSubscription:'添加订阅',lastError:'最近错误',
    keys:'API 密钥',profiles:'密钥配置档',projects:'项目',users:'用户',roles:'角色',invitations:'邀请',keysDescription:'管理项目密钥、网络策略、额度和有效期。',fingerprint:'指纹',ipPolicy:'IP 策略',anyIp:'任意 IP',restricted:'受限',tokenMode:'令牌模式',generateToken:'生成新令牌',importExisting:'导入现有令牌',existingToken:'现有令牌',generatedSecurity:'新令牌只显示一次，请立即安全保存。',importSecurity:'导入是一次性操作。鲮鲤只保存索引摘要和 Argon2id 校验哈希，不保存或返回明文。',importTokenHint:'32–1024 个高熵、无空白字符。保存后无法恢复。',importComplete:'令牌已导入，明文未保存。',profileId:'配置档 ID',budgetMicros:'预算（微美元）',allowedIps:'允许 IP/CIDR（逗号分隔）',deniedIps:'拒绝 IP/CIDR（逗号分隔）',profilesDescription:'配置模型映射、允许模型、RPM、TPM 与预算。',profileEmpty:'尚未创建密钥配置档。',addProfile:'添加配置档',routingPolicy:'路由策略',projectsDescription:'管理项目边界和所有者。',projectEmpty:'尚无可管理项目。',addProject:'添加项目',slug:'标识',ownerId:'所有者用户 ID',usersDescription:'管理本地用户和启用状态。',userEmpty:'尚无用户。',addUser:'添加用户',role:'角色',rolesDescription:'管理权限集合和项目角色。',roleEmpty:'尚无自定义角色。',addRole:'添加角色',scope:'范围',systemRole:'系统角色',permissions:'权限列表',invitationsDescription:'签发一次性项目邀请。',invitationEmpty:'尚无待处理邀请。',inviteUser:'邀请用户',roleId:'角色 ID',expiresSeconds:'有效秒数',expiresAt:'过期时间',acceptedAt:'接受时间',oidcDescription:'管理 OIDC、PKCE 和声明映射。',oidcEmpty:'尚未配置 OIDC。',addOidc:'添加 OIDC',issuer:'签发者 URL',clientId:'客户端 ID',clientSecret:'客户端密钥',scopes:'范围',claimMapping:'声明映射',secretConfigured:'已配置密钥',
    protection:'防护规则',overrides:'请求覆盖',promptsDescription:'管理可按条件注入的提示词。',promptEmpty:'尚未配置提示词。',addPrompt:'添加提示词',content:'内容',activation:'激活条件',protectionDescription:'在转发前拒绝或脱敏匹配内容。',protectionEmpty:'尚未配置防护规则。',addRule:'添加规则',rolePattern:'角色模式',contentPattern:'内容模式',action:'操作',deny:'拒绝',redact:'脱敏',replacement:'替换内容',testMode:'测试模式',overridesDescription:'管理渠道级端点、模型和参数覆盖。',overridesEmpty:'尚无渠道覆盖设置。',endpointMappings:'端点映射',modelRules:'模型规则',parameterOverrides:'参数覆盖',retryStatuses:'重试状态码',autoDisable:'自动停用',
    executions:'执行',threads:'会话线程',traces:'追踪',usage:'用量',costItems:'成本明细',audit:'审计',requestsDescription:'实时刷新最近请求，可按状态、供应商和模型筛选。',pause:'暂停刷新',resume:'继续刷新',executionsDescription:'查看每次上游尝试、重试原因与时序。',executionEmpty:'尚无执行记录。',requestId:'请求 ID',attempt:'尝试',retryReason:'重试原因',threadsDescription:'查看跨请求会话连续性。',threadEmpty:'尚无线程。',threadId:'线程 ID',externalId:'外部 ID',key:'密钥',tracesDescription:'查看线程到请求的追踪链路。',traceEmpty:'尚无追踪。',finishedAt:'结束时间',usageDescription:'查看权威用量和结算。',usageEmpty:'尚无用量记录。',executionId:'执行 ID',inputTokens:'输入 Token',outputTokens:'输出 Token',cacheTokens:'缓存 Token',settlement:'结算方式',costDescription:'查看逐组件成本。',costEmpty:'尚无成本明细。',usageId:'用量 ID',component:'组件',quantity:'数量',auditDescription:'查看控制平面安全审计。',auditEmpty:'尚无审计事件。',resourceId:'资源 ID',actor:'操作人',traceDetail:'追踪详情',backToRequests:'返回请求',backToTraces:'返回追踪',
    requestLogging:'请求日志',storage:'存储',backups:'备份',webhooks:'Webhook',jobs:'任务',retention:'保留策略',appearanceDescription:'配置语言、明暗模式和强调色。',interface:'界面',appearanceHint:'设置仅影响当前浏览器。',requestLoggingDescription:'站点策略决定请求正文能否被记录或由密钥覆盖。',enableRequestLogging:'启用请求日志',enableRequestLoggingHint:'关闭后仍保留最小用量、成本和安全审计事实。',defaultLevel:'默认级别',allowKeyOverrides:'允许密钥选择日志级别',allowKeyDisable:'允许密钥关闭可浏览日志',off:'关闭',metadata:'仅元数据',redacted_body:'脱敏正文',full_body:'完整正文',storageDescription:'管理本地或 S3 兼容目标。',storageEmpty:'尚未配置存储目标。',addStorage:'添加存储',configuration:'配置',revision:'修订版',storageSecret:'加密凭据 JSON',backupsDescription:'配置自动备份、探测与保留计划。',backupEmpty:'尚无计划。',addSchedule:'添加计划',automaticBackup:'自动备份',backupRetention:'备份保留',probe:'探测',quota:'配额',interval:'间隔',intervalSeconds:'间隔秒数',nextRun:'下次运行',webhooksDescription:'订阅渠道停用、配额和重复失败事件。',webhookEmpty:'尚无 Webhook。',addWebhook:'添加 Webhook',events:'事件',publicHeaders:'公开请求头',secretHeaders:'加密请求头',bodyTemplate:'正文模板',jobsDescription:'查看持久任务、重试和错误。',jobEmpty:'尚无任务。',attempts:'尝试次数',dueAt:'计划时间',retentionDescription:'管理请求、负载、探测和配额保留期。',retentionEmpty:'尚无保留策略。',addPolicy:'添加策略',retentionDays:'保留天数',retainPayloads:'保留负载',payloads:'负载',
    playgroundDescription:'使用一次性输入的 API 密钥调用 Responses API，密钥不会保存。',apiKey:'API 密钥',playgroundKeyHint:'仅保留在此表单中。',input:'输入',sendRequest:'发送请求',response:'响应',playgroundEmpty:'发送请求后在此查看原始响应。',
    securityDefaults: '安全默认值', securityCopy: '上游密钥采用本机主密钥加密；虚拟密钥和密码仅保存哈希；请求与响应正文默认不落盘。',
    deleteConfirm: '确认删除？此操作无法撤销。', formError: '请检查表单内容后重试。', networkError: '请求失败，请稍后重试。', healthy: '正常', degraded: '异常',
    noAccessSection: '当前权限下没有可用的访问控制模块。', statusCodeHint: '请输入三位状态码，例如 200 或 429。',
    about: '关于', aboutDescription: '核对控制台与后端的构建信息，确认运行中的两者来自同一次构建。', productName: 'Pangolin / 鲮鲤', backendBuild: '后端构建', consoleBuild: '控制台构建', commit: '提交', buildTime: '构建时间', buildTarget: '构建目标', buildProfile: '构建配置', buildMismatchTitle: '控制台与后端构建不一致', buildMismatchHint: '后端提交为 {{backend}}，当前控制台构建自 {{console}}。请先重新构建前端资源，再重新编译二进制，使两者来自同一提交。', copyDiagnostics: '复制诊断信息', copyFailed: '复制失败，请手动选择文本。',
  },
}

const en = {
  translation: {
    unrestricted:'Unrestricted',viewTrace:'View trace',
    invitationInvalid:'Invitation is invalid or expired',backToLogin:'Back to sign in',acceptInvitation:'Accept invitation',inspectInvitation:'Inspect invitation',invitedAs:'Invited email: {{email}}',displayName:'Display name',invitationCreated:'Invitation created',invitationOneTime:'This link is shown once. Send it securely to the invitee now.',accepted:'Accepted',pending:'Pending',noSearchResults:'No matching results',clearFilters:'Clear filters',pagination:'Pagination',previous:'Previous',next:'Next',pageSize:'Page size',copyId:'Copy ID',orchestrationSettings:'Orchestration settings',orchestrationSettingsHint:'Manage session affinity and optional conversation compaction.',affinityRules:'Affinity rules JSON',affinityRulesHint:'Up to 64 rules with a 1–86400 second TTL.',sessionCompaction:'Session compaction JSON',sessionCompactionHint:'Configure thresholds, retained items, and native or summarizer behavior before enabling.',channelPolicies:'Channel policies',channelPoliciesHint:'Manage endpoint maps, model rules, overrides, retries, and auto-disable behavior.',channelPoliciesEmpty:'No channel policies yet.',noProfile:'No profile',outcome:'Outcome',duration:'Duration',viewDetails:'View details',unknownProvider:'Unknown provider',noRetry:'No retry',rawIdentifiers:'Raw identifiers',statusSucceeded:'Succeeded',statusFinished:'Finished',statusFailed:'Failed',statusRunning:'Running',statusPending:'Pending',statusCancelled:'Cancelled',statusInterrupted:'Interrupted',statusUnknown:'Unknown',routingStageAccess:'Access check',routingStageMapping:'Model mapping',routingStageAssociation:'Routing rule',routingStageEligibility:'Eligibility check',routingStageHealth:'Health check',routingStageEndpoint:'Endpoint capability',routingStageStrategy:'Ordering strategy',routingStageProtection:'Prompt protection',routingStageOther:'Other decision',decisionAllowed:'Project and model access allowed',decisionMapped:'Profile model mapping applied',decisionMatched:'Rule matched',decisionOrdered:'Candidate ordered by routing strategy',decisionCircuitOpen:'Circuit breaker is open',decisionDisabled:'Channel or model is disabled',decisionTagPolicy:'Tag policy excludes this candidate',decisionHealthBackoff:'Channel is in health backoff',decisionQuotaExhausted:'Provider quota is exhausted',decisionUnsupported:'Endpoint or capability is unsupported',decisionOther:'{{code}}',onboardingTitle:'Complete initial setup',onboardingHint:'Add a channel, credential, and model route before sending requests.',
    localOverrides:'Local catalog overrides',overrideJson:'Override entry JSON',
    expiresAtEpoch:'Expires at, Unix seconds',
    download:'Download',
    identities:'OIDC identities',identitiesDescription:'Explicitly link an existing user to a verified provider subject.',oidcProviderId:'OIDC provider ID',subject:'Subject',claims:'Claims JSON',linkIdentity:'Link identity',
    oidc:'OIDC',channel:'Channel',
    noAccessibleProject:'No accessible project is available.',
    assignments:'Membership and role assignments',projectMembership:'Project membership',roleBinding:'Role binding',userId:'User ID',assign:'Assign',
    project:'Project',enable:'Enable',disable:'Disable',apply:'Apply',bulkActions:'Bulk enable or disable',resourceIds:'Resource IDs, comma separated',jobQueued:'Job queued',collectQuota:'Collect quota',runProbe:'Run probe',usePreset:'Use preset',preview:'Preview',orderedCandidates:'Ordered candidates',decisionLog:'Decision log',routingPreviewNeedsKey:'Create an enabled API key for this project first.',refresh:'Refresh',rollback:'Rollback',editSubscription:'Edit subscription',rollbackHint:'Select a verified snapshot to make active.',noSnapshots:'No snapshots are available.',signaturePolicy:'Signature policy',publicKey:'Ed25519 public key',none:'None',optional:'Optional',required:'Required',keyLoggingPolicy:'Per-key request logging',keyId:'Key ID',inherit:'Inherit site policy',editKey:'Edit API key',modelMappings:'Model mappings',allowedModels:'Allowed models',branding:'Branding and onboarding',brandingHint:'Configure the instance label, browser icon, and onboarding state.',brandingName:'Brand name',faviconUrl:'Favicon URL',onboardingComplete:'Onboarding complete',exportBackup:'Export backup',deliverBackup:'Deliver backup',restoreBackup:'Restore backup',resources:'Resources',resourcesHint:'Use database resource names, comma separated.',targetIds:'Storage target IDs',runNow:'Run now',artifactJson:'Backup artifact JSON',conflictStrategy:'Conflict strategy',restore:'Restore',backupSchedules:'Automatic schedules',backupScheduleHint:'Durable, revisioned backup and retention schedules.',
    product: 'Pangolin', productSubtitle: 'AI API gateway', overview: 'Overview', providers: 'Providers', models: 'Models & routes', apiKeys: 'API keys', requests: 'Requests', settings: 'Settings',
    signOut: 'Sign out', menu: 'Menu', close: 'Close', skipToContent: 'Skip to main content', dataTable: 'Data table', prefix: 'Prefix', trace: 'Trace ID', requestPayload: 'Request payload', responsePayload: 'Response payload', add: 'Add', cancel: 'Cancel', save: 'Save', delete: 'Delete', copy: 'Copy', copied: 'Copied', loading: 'Loading…', retry: 'Retry', noData: 'No data yet',
    setupTitle: 'Initialize Pangolin', setupIntro: 'Create the first administrator. Then add an upstream provider and issue virtual API keys.', instanceName: 'Instance name', email: 'Email', password: 'Password', passwordHint: 'At least 12 characters', createAdmin: 'Create administrator',
    loginTitle: 'Sign in to Pangolin', loginIntro: 'Enter your AI API control plane.', signIn: 'Sign in',
    last24h: 'Last 24 hours', totalRequests: 'Requests', errorRate: 'Error rate', p95Latency: 'P95 latency', tokenUsage: 'Token usage', cost: 'Cost', requestTrend: 'Request trend', recentRequests: 'Recent requests',
    failedRequests: '{{count}} failed', perRequest: 'per request', requestTrendHint: 'Request volume by hour', chartTooltipHint: 'Move the pointer over the line to inspect an hour.',
    providerName: 'Provider name', providerType: 'Type', baseUrl: 'Base URL', upstreamApiKey: 'Upstream API key', addProvider: 'Add provider', providerEmpty: 'Add an upstream provider first. Its key is encrypted on this machine.',
    publicModel: 'Public model name', upstreamModel: 'Upstream model', provider: 'Provider', priority: 'Priority', inputPrice: 'Input price', outputPrice: 'Output price', addModel: 'Add model', priceHint: 'micro-USD / million tokens', modelEmpty: 'Map a model so clients can call a stable public name.',
    keyName: 'Key name', budget: 'Budget', addKey: 'Create API key', keyCreated: 'API key created', keyCreatedHint: 'This is shown once. Copy and store it securely now.', keyEmpty: 'Create a virtual key for a client or team.', lastUsed: 'Last used', never: 'Never',
    status: 'Status', endpoint: 'Endpoint', startedAt: 'Started', latency: 'Latency', model: 'Model', tokens: 'Tokens', requestDetail: 'Request detail', payloadDisabled: 'Sensitive payload capture is off', payloadDisabledHint: 'This is the secure default. Metadata, usage and latency are still recorded.',
    appearance: 'Appearance', colorMode: 'Color mode', skin: 'Interface style', palette: 'Palette', accentTheme: 'Accent theme', language: 'Language', system: 'System', light: 'Light', dark: 'Dark', bronze: 'Bronze', slate: 'Slate', jade: 'Jade', skinHint: 'This style follows the catalogue\u2019s {{basis}} (material {{material}}, {{mode}} mode). Choosing a style also applies its recommended palette and mode.',
    workspace:'Workspace',observe:'Observe',administration:'Administration',primaryNavigation:'Primary navigation',channels:'Channels',operations:'Operations',access:'Access control',prompts:'Prompts',playground:'Playground',systemSettings:'System settings',actions:'Actions',edit:'Edit',saved:'Saved',deleted:'Deleted',search:'Search',retryHint:'Check the connection and try again.',invalidJson:'The JSON is invalid.',viewAll:'View all',name:'Name',enabled:'Enabled',disabled:'Disabled',type:'Type',version:'Version',statusCode:'Status code',time:'Time',ready:'Ready',catalogOnly:'Catalog only',
    overviewEmptyTitle:'No requests in the last 24 hours',overviewEmptyCopy:'Configure a channel and model route, then send a request from a client.',configureChannel:'Configure a channel',noRequests24h:'No requests are available in the last 24 hours.',credentials:'Credentials',probes:'Probes',quotas:'Quotas',presets:'Presets',channelsDescription:'Manage upstream channels, availability, and endpoints.',channelEmpty:'Add a channel, then attach one or more encrypted credentials.',addChannel:'Add channel',credentialsDescription:'Use multiple encrypted credentials per channel, ordered by priority.',credentialEmpty:'Add the first credential for a channel.',addCredential:'Add credential',credentialType:'Credential type',channelId:'Channel ID',suffix:'Suffix',secret:'Secret',secretUpdateHint:'Submit a secret only when creating or rotating. It cannot be recovered after saving.',advancedSettings:'Advanced settings',probesDescription:'Inspect channel health checks and latency.',probeEmpty:'No probe results yet.',quotasDescription:'Inspect provider quota snapshots.',quotaEmpty:'No quota snapshots yet.',remaining:'Remaining',periodEnd:'Period end',presetsDescription:'Built-in offline provider catalog for channel setup.',presetEmpty:'No provider preset matches.',adapter:'Adapter',
    routing:'Model routing',prices:'Prices',catalog:'Model catalog',subscriptions:'Subscriptions',modelsDescription:'Manage public models, capabilities, and upstream mappings.',capabilities:'Capabilities',routingDescription:'Compose channel candidates with exact, regex, or tag rules.',routingEmpty:'Add the first model association.',addRoute:'Add route',matchType:'Match type',pattern:'Pattern',weight:'Weight',modelId:'Model ID',conditions:'Conditions',routingPreview:'Routing preview and explanation',routingPreviewHint:'Enter a requested model and tags to preview ordered matches.',requestedModel:'Requested model',tags:'Tags, comma separated',noRouteMatch:'No rule matches this input.',routeExplanation:'Priority {{priority}}, weight {{weight}}, channel {{channel}}',pricesDescription:'Price versions remain immutable after use.',priceEmpty:'No price versions yet.',addPrice:'Add price',validFrom:'Valid from',validUntil:'Valid until',schedule:'Schedule',priceComponents:'Price components',catalogDescription:'Inspect catalog models, capabilities, and sources.',catalogEmpty:'No catalog models match.',catalogResultCount:'{{count}} models',moreCapabilities:'+{{count}} more',catalogTransfer:'Catalog import and export',catalogTransferHint:'Imports are validated before atomic activation.',export:'Export',import:'Import',catalogJson:'Catalog JSON',validateAndImport:'Validate and import',subscriptionsDescription:'Manage HTTPS catalog subscriptions, signatures, and refresh order.',subscriptionEmpty:'No catalog subscriptions configured.',addSubscription:'Add subscription',lastError:'Last error',
    keys:'API keys',profiles:'Key profiles',projects:'Projects',users:'Users',roles:'Roles',invitations:'Invitations',keysDescription:'Manage project keys, network policy, budgets, and expiry.',fingerprint:'Fingerprint',ipPolicy:'IP policy',anyIp:'Any IP',restricted:'Restricted',tokenMode:'Token mode',generateToken:'Generate token',importExisting:'Import existing',existingToken:'Existing token',generatedSecurity:'The new token is shown once. Store it securely now.',importSecurity:'Import is one-time. Pangolin stores only an indexed digest and Argon2id verification hash, never the plaintext token.',importTokenHint:'32–1024 high-entropy characters with no whitespace. It cannot be recovered.',importComplete:'Token imported. Plaintext was not retained.',profileId:'Profile ID',budgetMicros:'Budget, micro-USD',allowedIps:'Allowed IP/CIDR, comma separated',deniedIps:'Denied IP/CIDR, comma separated',profilesDescription:'Configure model mapping, allowlists, RPM, TPM, and budget.',profileEmpty:'No key profiles yet.',addProfile:'Add profile',routingPolicy:'Routing policy',projectsDescription:'Manage project boundaries and ownership.',projectEmpty:'No manageable projects.',addProject:'Add project',slug:'Slug',ownerId:'Owner user ID',usersDescription:'Manage local users and status.',userEmpty:'No users yet.',addUser:'Add user',role:'Role',rolesDescription:'Manage permission sets and project roles.',roleEmpty:'No custom roles yet.',addRole:'Add role',scope:'Scope',systemRole:'System role',permissions:'Permissions',invitationsDescription:'Issue one-time project invitations.',invitationEmpty:'No pending invitations.',inviteUser:'Invite user',roleId:'Role ID',expiresSeconds:'Expires in seconds',expiresAt:'Expires',acceptedAt:'Accepted',oidcDescription:'Manage OIDC, PKCE, and claim mapping.',oidcEmpty:'No OIDC provider configured.',addOidc:'Add OIDC',issuer:'Issuer URL',clientId:'Client ID',clientSecret:'Client secret',scopes:'Scopes',claimMapping:'Claim mapping',secretConfigured:'Secret configured',
    protection:'Protection',overrides:'Request overrides',promptsDescription:'Manage conditionally injected prompts.',promptEmpty:'No prompts configured.',addPrompt:'Add prompt',content:'Content',activation:'Activation',protectionDescription:'Deny or redact matching content before forwarding.',protectionEmpty:'No protection rules configured.',addRule:'Add rule',rolePattern:'Role pattern',contentPattern:'Content pattern',action:'Action',deny:'Deny',redact:'Redact',replacement:'Replacement',testMode:'Test mode',overridesDescription:'Manage per-channel endpoint, model, and parameter overrides.',overridesEmpty:'No channel overrides yet.',endpointMappings:'Endpoint mappings',modelRules:'Model rules',parameterOverrides:'Parameter overrides',retryStatuses:'Retry statuses',autoDisable:'Auto-disable',
    executions:'Executions',threads:'Threads',traces:'Traces',usage:'Usage',costItems:'Cost items',audit:'Audit',requestsDescription:'Recent requests refresh live and can be filtered by status, provider, and model.',pause:'Pause',resume:'Resume',executionsDescription:'Inspect every upstream attempt, retry reason, and timing.',executionEmpty:'No executions yet.',requestId:'Request ID',attempt:'Attempt',retryReason:'Retry reason',threadsDescription:'Inspect cross-request conversation continuity.',threadEmpty:'No threads yet.',threadId:'Thread ID',externalId:'External ID',key:'Key',tracesDescription:'Inspect the thread-to-request trace chain.',traceEmpty:'No traces yet.',finishedAt:'Finished',usageDescription:'Inspect authoritative usage and settlement.',usageEmpty:'No usage records yet.',executionId:'Execution ID',inputTokens:'Input tokens',outputTokens:'Output tokens',cacheTokens:'Cache tokens',settlement:'Settlement',costDescription:'Inspect itemized costs.',costEmpty:'No cost items yet.',usageId:'Usage ID',component:'Component',quantity:'Quantity',auditDescription:'Inspect control-plane security audit events.',auditEmpty:'No audit events yet.',resourceId:'Resource ID',actor:'Actor',traceDetail:'Trace detail',backToRequests:'Back to requests',backToTraces:'Back to traces',
    requestLogging:'Request logging',storage:'Storage',backups:'Backups',webhooks:'Webhooks',jobs:'Jobs',retention:'Retention',appearanceDescription:'Configure language, color mode, and accent.',interface:'Interface',appearanceHint:'These settings affect this browser only.',requestLoggingDescription:'Site policy controls whether bodies may be logged or overridden by keys.',enableRequestLogging:'Enable request logging',enableRequestLoggingHint:'Disabling browsable logs still retains minimum usage, cost, and security audit facts.',defaultLevel:'Default level',allowKeyOverrides:'Allow key-level log choices',allowKeyDisable:'Allow keys to disable browsable logs',off:'Off',metadata:'Metadata only',redacted_body:'Redacted body',full_body:'Full body',storageDescription:'Manage local or S3-compatible targets.',storageEmpty:'No storage target configured.',addStorage:'Add storage',configuration:'Configuration',revision:'Revision',storageSecret:'Encrypted credentials JSON',backupsDescription:'Configure automatic backup, probes, and retention schedules.',backupEmpty:'No schedules yet.',addSchedule:'Add schedule',automaticBackup:'Automatic backup',backupRetention:'Backup retention',probe:'Probe',quota:'Quota',interval:'Interval',intervalSeconds:'Interval seconds',nextRun:'Next run',webhooksDescription:'Subscribe to channel disable, quota, and repeated failure events.',webhookEmpty:'No webhooks yet.',addWebhook:'Add webhook',events:'Events',publicHeaders:'Public headers',secretHeaders:'Encrypted headers',bodyTemplate:'Body template',jobsDescription:'Inspect durable work, retries, and errors.',jobEmpty:'No jobs yet.',attempts:'Attempts',dueAt:'Due at',retentionDescription:'Manage request, payload, probe, and quota retention.',retentionEmpty:'No retention policy yet.',addPolicy:'Add policy',retentionDays:'Retention days',retainPayloads:'Retain payloads',payloads:'Payloads',playgroundDescription:'Call the Responses API with a one-time API key. The key is not stored.',apiKey:'API key',playgroundKeyHint:'Kept only in this form.',input:'Input',sendRequest:'Send request',response:'Response',playgroundEmpty:'Send a request to inspect the raw response here.',
    securityDefaults: 'Security defaults', securityCopy: 'Upstream secrets are encrypted by a local master key; virtual keys and passwords are hashed; request and response bodies are not stored by default.',
    deleteConfirm: 'Delete this item? This cannot be undone.', formError: 'Check the form and try again.', networkError: 'The request failed. Try again shortly.', healthy: 'Healthy', degraded: 'Degraded',
    noAccessSection: 'No access-control modules are available for your permissions.', statusCodeHint: 'Enter a three-digit status code, for example 200 or 429.',
    about: 'About', aboutDescription: 'Compare the console and backend build identity to confirm the running pair matches.', productName: 'Pangolin / 鲮鲤', backendBuild: 'Backend build', consoleBuild: 'Console build', commit: 'Commit', buildTime: 'Built at', buildTarget: 'Target', buildProfile: 'Profile', buildMismatchTitle: 'Console and backend builds differ', buildMismatchHint: 'The backend reports commit {{backend}} while this console was built from {{console}}. Rebuild the web assets, then recompile the binary, so both come from the same revision.', copyDiagnostics: 'Copy diagnostics', copyFailed: 'Copy failed. Select the text manually.',
  },
}

const storedLanguage = localStorage.getItem('pangolin-language') || (navigator.language.startsWith('zh') ? 'zh-CN' : 'en')

void i18n.use(initReactI18next).init({ resources: { 'zh-CN': zh, en }, lng: storedLanguage, fallbackLng: 'en', interpolation: { escapeValue: false } })
document.documentElement.lang = storedLanguage

i18n.on('languageChanged', (language) => {
  localStorage.setItem('pangolin-language', language)
  document.documentElement.lang = language
})

export default i18n
